version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: domainmapper-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: domainmapper2024
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - domainmapper-network

  backend:
    build: .
    container_name: domainmapper-backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:domainmapper2024@mongodb:27017/
      SHODAN_API_KEY: ${SHODAN_API_KEY:-}
      VIRUSTOTAL_API_KEY: ${VIRUSTOTAL_API_KEY:-}
    ports:
      - "8001:8001"
    volumes:
      - ./history:/app/history
      - ./reports:/app/reports
      - ./wordlists:/app/wordlists
    depends_on:
      - mongodb
    networks:
      - domainmapper-network
    command: uvicorn backend.server:app --host 0.0.0.0 --port 8001 --reload

volumes:
  mongodb_data:
    driver: local

networks:
  domainmapper-network:
    driver: bridge